"use client";

import { useActionState, useState } from "react";
import { ArrowDown, ArrowUp, ExternalLink, Pencil, Plus, Trash2 } from "lucide-react";

import { deleteQuickLinkAction, moveQuickLinkAction, saveQuickLinkAction, type QuickLinkActionState } from "@/app/(app)/quick-links/actions";
import type { QuickLink } from "@/lib/quick-links/repository";

const initialState: QuickLinkActionState = { status: "idle" };
const iconOptions = [["document", "문서"], ["spreadsheet", "스프레드시트"], ["drive", "드라이브"], ["school", "학교"], ["admin", "행정"], ["health", "건강"], ["web", "웹"], ["other", "기타"]] as const;
function emptyDraft(): QuickLink { return { id: "", userId: "", name: "", url: "https://", iconKey: "web", sortOrder: 0, isVisible: true, createdAt: "", updatedAt: "" }; }

export function QuickLinksManager({ links }: { readonly links: readonly QuickLink[] }) {
  const [editing, setEditing] = useState<QuickLink | null>(null);
  const [state, action, pending] = useActionState(saveQuickLinkAction, initialState);
  const sorted = [...links].sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name, "ko"));
  return <section className="quick-links-manager"><div className="quick-links-manager__toolbar"><p>Today 우측 카드에 표시할 링크를 관리합니다.</p><button className="button button--primary" onClick={() => setEditing(emptyDraft())} type="button"><Plus aria-hidden="true" size={16} />링크 추가</button></div>{sorted.length === 0 ? <div className="quick-links-manager__empty"><h2>자주 쓰는 사이트를 등록해보세요.</h2><button className="button button--primary" onClick={() => setEditing(emptyDraft())} type="button"><Plus aria-hidden="true" size={16} />첫 링크 추가</button></div> : <div className="quick-links-manager__list">{sorted.map((link, index) => <article className="quick-links-manager__item" key={link.id}><div><strong>{link.name}</strong><a href={link.url} rel="noopener noreferrer" target="_blank">{link.url}<ExternalLink aria-hidden="true" size={13} /></a><small>{link.isVisible ? "Today에 표시" : "숨김"}</small></div><div className="quick-links-manager__actions"><form action={moveQuickLinkAction}><input name="id" type="hidden" value={link.id} /><input name="direction" type="hidden" value="up" /><button aria-label={`${link.name} 위로`} disabled={index === 0} type="submit"><ArrowUp aria-hidden="true" size={15} /></button></form><form action={moveQuickLinkAction}><input name="id" type="hidden" value={link.id} /><input name="direction" type="hidden" value="down" /><button aria-label={`${link.name} 아래로`} disabled={index === sorted.length - 1} type="submit"><ArrowDown aria-hidden="true" size={15} /></button></form><button aria-label={`${link.name} 수정`} onClick={() => setEditing(link)} type="button"><Pencil aria-hidden="true" size={15} /></button><form action={deleteQuickLinkAction}><input name="id" type="hidden" value={link.id} /><button aria-label={`${link.name} 삭제`} type="submit"><Trash2 aria-hidden="true" size={15} /></button></form></div></article>)}</div>}{editing && <form action={action} className="quick-links-manager__form"><input name="id" type="hidden" value={editing.id} /><input name="sortOrder" type="hidden" value={editing.sortOrder} /><label>이름<input defaultValue={editing.name} name="name" required /></label><label>URL<input defaultValue={editing.url} name="url" required type="url" /></label><label>카테고리<select defaultValue={editing.iconKey} name="iconKey">{iconOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="quick-links-manager__checkbox"><input defaultChecked={editing.isVisible} name="isVisible" type="checkbox" />Today에 표시</label>{state.message && <p className={state.status === "error" ? "form-message is-error" : "form-message"} role={state.status === "error" ? "alert" : "status"}>{state.message}</p>}<div><button className="button button--primary" disabled={pending} type="submit">{pending ? "저장 중..." : "저장"}</button><button className="button button--secondary" onClick={() => setEditing(null)} type="button">취소</button></div></form>}</section>;
}
