import { PageHeader } from "@/components/layout/page-header";
import { parseReportFilters, REPORT_STATUS_LABELS, REPORT_STATUSES, REPORT_TYPE_LABELS, REPORT_TYPES } from "@/lib/reports/model";
import { listAllReports } from "@/lib/reports/repository";
import { updateReportAction } from "@/app/(app)/support/reports/actions";

export default async function AdminReportsPage({ searchParams }: { readonly searchParams: Promise<{ readonly type?: string; readonly status?: string }> }) {
  const params = await searchParams;
  const filters = parseReportFilters(params);
  const reports = await listAllReports(filters);
  const reportType = filters.reportType;
  const status = filters.status;
  return <main className="page-canvas admin-reports-page"><PageHeader description="사용자 신고를 확인하고 처리 상태를 관리합니다." eyebrow="관리자" title="오류·문의 신고 관리" /><form className="admin-report-filters" method="get"><label>신고 유형<select defaultValue={reportType ?? ""} name="type"><option value="">전체</option>{REPORT_TYPES.map((type) => <option key={type} value={type}>{REPORT_TYPE_LABELS[type]}</option>)}</select></label><label>상태<select defaultValue={status ?? ""} name="status"><option value="">전체</option>{REPORT_STATUSES.map((value) => <option key={value} value={value}>{REPORT_STATUS_LABELS[value]}</option>)}</select></label><button className="button button--secondary" type="submit">필터 적용</button></form><section className="admin-report-list">{reports.length === 0 ? <p className="report-empty">조건에 맞는 신고가 없습니다.</p> : reports.map((report) => <article className="admin-report-card" key={report.id}><header><div><span>{REPORT_TYPE_LABELS[report.reportType]}</span><h2>{report.title}</h2><small>{report.userId} · {new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(report.createdAt))}</small></div><span className="report-status">{REPORT_STATUS_LABELS[report.status]}</span></header><details><summary>신고 내용 보기</summary><div className="admin-report-card__content"><p>{report.description}</p>{report.attemptedAction && <p><b>하려고 했던 작업</b>{report.attemptedAction}</p>}{report.observedResult && <p><b>발생한 현상</b>{report.observedResult}</p>}<small>경로: {report.pagePath} · 화면: {report.viewportWidth ?? "-"} × {report.viewportHeight ?? "-"}</small></div></details><form action={updateReportAction} className="admin-report-card__form"><input name="id" type="hidden" value={report.id} /><label>상태<select defaultValue={report.status} name="status">{REPORT_STATUSES.map((value) => <option key={value} value={value}>{REPORT_STATUS_LABELS[value]}</option>)}</select></label><label>관리자 메모<textarea defaultValue={report.adminNote ?? ""} maxLength={10000} name="adminNote" rows={2} /></label><button className="button button--secondary" type="submit">상태 저장</button></form></article>)}</section></main>;
}
