"use client";

import { Bell, CalendarClock, Check, LayoutDashboard, LogOut, Sparkles, UserRound } from "lucide-react";
import { useActionState } from "react";

import { saveSettingsAction, type SettingsActionState } from "@/app/(app)/settings/actions";
import { CalendarPreferencesCard } from "@/components/settings/calendar-preferences-card";
import type { UserSettingsInput } from "@/lib/settings/domain";

const initialState: SettingsActionState = { status: "idle" };

function ToggleRow({ defaultChecked, description, icon: Icon, label, name }: { readonly defaultChecked: boolean; readonly description: string; readonly icon: typeof Bell; readonly label: string; readonly name: string }) {
  return <label className="settings-toggle-row"><span className="settings-row-icon"><Icon aria-hidden="true" size={18} /></span><span><strong>{label}</strong><small>{description}</small></span><input defaultChecked={defaultChecked} name={name} type="checkbox" /><span aria-hidden="true" className="settings-switch"><span /></span></label>;
}

export function SettingsForm({ email, initialValues }: { readonly email: string; readonly initialValues: UserSettingsInput }) {
  const [state, action, pending] = useActionState(saveSettingsAction, initialState);
  return <form action={action} className="settings-form"><input name="weekStartsOn" type="hidden" value={initialValues.weekStartsOn} /><CalendarPreferencesCard /><section className="settings-card"><div className="settings-card__heading"><CalendarClock aria-hidden="true" size={20} /><div><h2>일반</h2><p>일정 입력의 기본 방식을 정합니다.</p></div></div><div className="settings-field-grid"><label>기본 일정 시간<select defaultValue={String(initialValues.defaultEventMinutes)} name="defaultEventMinutes"><option value="15">15분</option><option value="30">30분</option><option value="60">60분</option><option value="90">90분</option><option value="120">120분</option></select></label></div></section><section className="settings-card"><div className="settings-card__heading"><Bell aria-hidden="true" size={20} /><div><h2>알림</h2><p>필요한 업무 알림만 켜둘 수 있습니다.</p></div></div><ToggleRow defaultChecked={initialValues.eventRemindersEnabled} description="일정 시작 전에 알림을 준비합니다." icon={CalendarClock} label="일정 알림" name="eventRemindersEnabled" /><ToggleRow defaultChecked={initialValues.taskDueRemindersEnabled} description="업무 마감일을 놓치지 않도록 알립니다." icon={Check} label="업무 마감 알림" name="taskDueRemindersEnabled" /></section><section className="settings-card"><div className="settings-card__heading"><Sparkles aria-hidden="true" size={20} /><div><h2>기능</h2><p>사용할 기능을 선택합니다.</p></div></div><ToggleRow defaultChecked={initialValues.exerciseEnabled} description="운동 스티커와 월간 기록을 표시합니다." icon={Check} label="운동 기록" name="exerciseEnabled" /><ToggleRow defaultChecked={initialValues.writingAssistanceEnabled} description="업무 내용과 체크리스트 제안을 사용합니다." icon={Sparkles} label="작성 도움" name="writingAssistanceEnabled" /></section><section className="settings-card"><div className="settings-card__heading"><LayoutDashboard aria-hidden="true" size={20} /><div><h2>화면</h2><p>한 화면에 보이는 정보의 간격을 조절합니다.</p></div></div><fieldset className="density-options"><legend>화면 밀도</legend>{[["default", "기본"], ["comfortable", "여유 있게"], ["compact", "조밀하게"]].map(([value, label]) => <label key={value}><input defaultChecked={initialValues.displayDensity === value} name="displayDensity" type="radio" value={value} /><span>{label}</span></label>)}</fieldset></section><section className="settings-card settings-account"><div className="settings-card__heading"><UserRound aria-hidden="true" size={20} /><div><h2>계정</h2><p>Google 계정으로 안전하게 연결되어 있습니다.</p></div></div><div className="settings-account__row"><div><strong>{email}</strong><span><i aria-hidden="true" />동기화됨</span></div><button form="settings-logout-form" type="submit"><LogOut aria-hidden="true" size={17} />로그아웃</button></div></section><div className="settings-save-bar"><div>{state.message && <p aria-live="polite" className={state.status === "error" ? "form-message form-message--error" : "form-message"}>{state.message}</p>}</div><button className="button" disabled={pending} type="submit">{pending ? "저장 중…" : "설정 저장"}</button></div></form>;
}
