"use client";

import { CalendarPlus, ClipboardCopy, Clock3, MoreHorizontal, Repeat2 } from "lucide-react";

import { cloneBuiltInTemplateAction } from "@/app/(app)/work-item-actions";
import { useAppShellCreate } from "@/components/layout/app-shell-create-context";
import { TASK_CATEGORY_OPTIONS } from "@/lib/work-items/categories";
import type { TemplateDefinition } from "@/lib/work-items/workflow";

const categoryLabels = new Map(TASK_CATEGORY_OPTIONS.map((item) => [item.value, item.label]));

export function TemplateGallery({ builtIn, custom }: { readonly builtIn: readonly TemplateDefinition[]; readonly custom: readonly TemplateDefinition[] }) {
  const { openCreate } = useAppShellCreate();
  return <div className="template-sections">
    <section aria-labelledby="built-in-template-title"><div className="section-title-row"><div><h2 id="built-in-template-title">기본 템플릿</h2><p>보건업무 단위의 안전한 기본값입니다.</p></div><span>{builtIn.length}개</span></div><div className="template-grid">{builtIn.map((template) => <article className="template-card" key={template.key}><div className="template-card__header"><span className={`category-dot category-dot--${template.category}`} /><div><strong>{template.name}</strong><small>{categoryLabels.get(template.category)}</small></div><details className="template-card__more"><summary aria-label={`${template.name} 더보기`}><MoreHorizontal size={18} /></summary><div className="template-card__menu"><form action={cloneBuiltInTemplateAction}><input name="key" type="hidden" value={template.key} /><button type="submit"><ClipboardCopy size={15} />내 템플릿으로 복제</button></form></div></details></div><p>{template.description}</p><div className="template-card__meta"><span><Clock3 size={13} />예상 {template.estimatedMinutes}분</span><span>권장 {template.recommendedTiming}</span><span>{template.checklist.length}개 체크</span>{template.recurrenceFrequency && <span><Repeat2 size={13} />반복 설정</span>}</div><div className="template-card__actions"><button className="button button--primary" onClick={(event) => openCreate(event.currentTarget, template.kind, template)} type="button"><CalendarPlus size={15} />적용</button></div></article>)}</div></section>
    <section aria-labelledby="custom-template-title"><div className="section-title-row"><div><h2 id="custom-template-title">내 템플릿</h2><p>기본 템플릿을 복제하거나 지난 업무에서 저장한 항목입니다.</p></div><span>{custom.length}개</span></div>{custom.length ? <div className="template-grid">{custom.map((template) => <article className="template-card" key={template.key}><div className="template-card__header"><span className={`category-dot category-dot--${template.category}`} /><div><strong>{template.name}</strong><small>{categoryLabels.get(template.category)}</small></div><details className="template-card__more"><summary aria-label={`${template.name} 더보기`}><MoreHorizontal size={18} /></summary><div className="template-card__menu template-card__menu--info"><span>내 템플릿</span><small>{template.recurrenceFrequency ? "반복 설정 포함" : "반복 설정 없음"}</small></div></details></div><p>{template.description || "설명 없음"}</p><div className="template-card__meta"><span>{template.checklist.length}개 체크</span>{template.recurrenceFrequency && <span><Repeat2 size={13} />반복 설정</span>}</div><div className="template-card__actions"><button className="button button--primary" onClick={(event) => openCreate(event.currentTarget, template.kind, template)} type="button"><CalendarPlus size={15} />적용</button></div></article>)}</div> : <div className="empty-state compact-empty"><ClipboardCopy /><div><h3>저장한 템플릿이 없습니다.</h3><p>기본 템플릿을 복제하거나 완료 업무를 템플릿으로 저장해 보세요.</p></div></div>}</section>
  </div>;
}
